package edu.hubanato.forms;

import edu.hubanato.controlers.AmortizationCalc;
import java.awt.print.PrinterException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Tony
 */
public class AmortizationScheduleForm extends javax.swing.JFrame{

    private AmortizationCalc am;
    DefaultCategoryDataset dataset = new DefaultCategoryDataset();
    
    public AmortizationScheduleForm() {
        initComponents();
        //am = new AmortizationCalc(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        amortizationTable = new javax.swing.JTable();
        printButton = new javax.swing.JButton();
        labelAmount = new javax.swing.JLabel();
        labelDuration = new javax.swing.JLabel();
        labelRate = new javax.swing.JLabel();
        labelInsurance = new javax.swing.JLabel();
        buttonGraph = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        amortizationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mois", "Capital amorti", "Intérêts", "Capital restant", "Mensualité", "Assurance", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(amortizationTable);

        printButton.setText("Imprimer");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        labelAmount.setText("Montant de l'emprunt: ");

        labelDuration.setText("Durée du prêt: ");

        labelRate.setText("Taux annuel: ");

        labelInsurance.setText("Taux d'assurance: ");

        buttonGraph.setText("Graphe");
        buttonGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGraphActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAmount)
                    .addComponent(labelDuration)
                    .addComponent(labelRate)
                    .addComponent(labelInsurance)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(printButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonGraph)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAmount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDuration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelRate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelInsurance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printButton)
                    .addComponent(buttonGraph))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed

        try {
            /* print the table */
            boolean complete = this.amortizationTable.print();

            /* if printing completes */
            if (complete) {
                /* show a success message */
                JOptionPane.showMessageDialog(this,
                                              "Impression envoyé",
                                              "Information",
                                              JOptionPane.INFORMATION_MESSAGE);
            } else {
                /* show a message indicating that printing was cancelled */
                JOptionPane.showMessageDialog(this,
                                              "Impression annulée",
                                              "Information",
                                              JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (PrinterException pe) {
            /* Printing failed, report to the user */
            JOptionPane.showMessageDialog(this,
                                          "Impression échouée: " + pe.getMessage(),
                                          "Information",
                                          JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_printButtonActionPerformed

    private void buttonGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGraphActionPerformed
        JFreeChart lineChart = ChartFactory.createLineChart(
         "Courbe de paiment",
         "Montant","Mois",
         dataImport(),
         PlotOrientation.VERTICAL,
         true,true,false);
        
        ChartPanel pan1 = new ChartPanel(lineChart, false);
        pan1.setBounds(0,0,0,0);

        this.add(pan1);
        this.setVisible(true);
        this.setSize(100,100);
        this.repaint();
    }//GEN-LAST:event_buttonGraphActionPerformed
    
    private DefaultCategoryDataset dataImport( )
   {
      //DefaultCategoryDataset dataset = new DefaultCategoryDataset( );
      return dataset;
   }
    
    public void insertData(double amount, int month){
        dataset.addValue( amount , "Montant" , String.valueOf(month) );
    }
    
    public JTable getTable(){
        return amortizationTable;
    }
    
    public JLabel getLabelAMount(){
        return labelAmount;
    }
    
    public JLabel getLabelDuration(){
        return labelDuration;
    }
    
    public JLabel getLabelInsurance(){
        return labelInsurance;
    }
    
    public JLabel getLabelRate(){
        return labelRate;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable amortizationTable;
    private javax.swing.JButton buttonGraph;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelAmount;
    private javax.swing.JLabel labelDuration;
    private javax.swing.JLabel labelInsurance;
    private javax.swing.JLabel labelRate;
    private javax.swing.JButton printButton;
    // End of variables declaration//GEN-END:variables


}
