package edu.hubanato.forms;

import edu.hubanato.client.TCPClient;
import edu.hubanato.entities.Client;
import java.io.IOException;
import java.sql.SQLException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Tom
 */
public class AuthenticationClientForm extends javax.swing.JFrame {
    
    private List<Client> clients = new ArrayList<Client>(); // searchedClients
    
    /**
     * Creates new form AuthenticationClientForm
     */
    public AuthenticationClientForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitle = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        firstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        postalCode = new javax.swing.JLabel();
        txtPostalCode = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnNewClient = new javax.swing.JButton();
        client = new javax.swing.JLabel();
        btnAuthenticate = new javax.swing.JButton();
        cmbClients = new javax.swing.JComboBox();
        labelResultResearch = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Authentifier un client");

        labelTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(0, 51, 102));
        labelTitle.setText("Authentification du client");

        name.setText("Nom :");

        firstName.setText("Prénom :");

        txtFirstName.setPreferredSize(new java.awt.Dimension(100, 20));

        postalCode.setText("Code postal :");

        txtPostalCode.setPreferredSize(new java.awt.Dimension(50, 20));

        btnSearch.setText("Rechercher");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnNewClient.setText("Nouveau Client");
        btnNewClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewClientActionPerformed(evt);
            }
        });

        client.setText("Client :");

        btnAuthenticate.setText("Authentifier");
        btnAuthenticate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthenticateActionPerformed(evt);
            }
        });

        labelResultResearch.setPreferredSize(new java.awt.Dimension(100, 23));

        txtName.setPreferredSize(new java.awt.Dimension(100, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(name)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(firstName)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(postalCode)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSearch)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelResultResearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(client)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbClients, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAuthenticate))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(labelTitle)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnNewClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitle)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(firstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(postalCode)
                    .addComponent(txtPostalCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSearch)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelResultResearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(client)
                            .addComponent(cmbClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAuthenticate))))
                .addGap(18, 18, 18)
                .addComponent(btnNewClient)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Start the clients research in database
     * @param evt 
     */
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        
        cmbClients.removeAllItems();// empty the comboBox before any research
        
        String name = txtName.getText(), firstName = txtFirstName.getText(), postalCode = txtPostalCode.getText();
        
        if (name.isEmpty()) name = "%";
        if (firstName.isEmpty()) firstName = "%";
        if (postalCode.isEmpty()) postalCode = "%";
        
        try {
            TCPClient tcpClient = new TCPClient("localhost",9999);
            List<String> liste = new ArrayList<String>();
            liste.add(name); liste.add(firstName); liste.add(postalCode);
            tcpClient.sendQuery("gc", edu.hubanato.serialization.EncodeJSON.serializeListString(liste));
            clients = edu.hubanato.serialization.DecodeJSON.deserializeClients(tcpClient.receiveQuery());
        } catch (IOException ex) {
            Logger.getLogger(AuthenticationClientForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        labelResultResearch.setText(clients.size() + " résultat(s)");
        for (int i = 0; i < clients.size(); i++) {
            cmbClients.addItem("Nom : " + clients.get(i).getName().toUpperCase() + " " + clients.get(i).getFirstName() + " / Code postal : " + clients.get(i).getCp());
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed
    
    /**
     * Start of ClientForm
     * @param evt 
     */
    private void btnNewClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewClientActionPerformed
        new ClientForm().setVisible(true);
    }//GEN-LAST:event_btnNewClientActionPerformed
    
    /**
     * Start of SimulationForm with the selected client in parameter
     * @param evt 
     */
    private void btnAuthenticateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthenticateActionPerformed
        if (cmbClients.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Veuillez selectionner un client.", "Erreur de selection", JOptionPane.ERROR_MESSAGE);
        } else {
            this.setVisible(false);
            Client client =  clients.get(cmbClients.getSelectedIndex());
            new SimulationForm(client).setVisible(true);
        }
    }//GEN-LAST:event_btnAuthenticateActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAuthenticate;
    private javax.swing.JButton btnNewClient;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel client;
    private javax.swing.JComboBox cmbClients;
    private javax.swing.JLabel firstName;
    private javax.swing.JLabel labelResultResearch;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel name;
    private javax.swing.JLabel postalCode;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPostalCode;
    // End of variables declaration//GEN-END:variables
}
