package edu.hubanato.forms;

import edu.hubanato.entities.Client;
import java.sql.SQLException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Tom
 */
public class AuthenticationClientForm extends javax.swing.JFrame {
    
    private List<Client> clients = new ArrayList<Client>(); // searchedClients
    
    /**
     * Creates new form AuthenticationClientForm
     */
    public AuthenticationClientForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitle = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        firstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        postalCode = new javax.swing.JLabel();
        txtPostalCode = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnNewClient = new javax.swing.JButton();
        client = new javax.swing.JLabel();
        btnAuthenticate = new javax.swing.JButton();
        cmbClients = new javax.swing.JComboBox();
        labelResultResearch = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(0, 51, 102));
        labelTitle.setText("Authentification du client");

        name.setText("Nom :");

        firstName.setText("Prénom :");

        txtFirstName.setPreferredSize(new java.awt.Dimension(100, 20));

        postalCode.setText("Code postal :");

        txtPostalCode.setPreferredSize(new java.awt.Dimension(50, 20));

        btnSearch.setText("Rechercher");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnNewClient.setText("Nouveau Client");
        btnNewClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewClientActionPerformed(evt);
            }
        });

        client.setText("Client :");

        btnAuthenticate.setText("Authentifier");
        btnAuthenticate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthenticateActionPerformed(evt);
            }
        });

        labelResultResearch.setPreferredSize(new java.awt.Dimension(100, 23));

        txtName.setPreferredSize(new java.awt.Dimension(100, 20));

        btnBack.setText("Retour");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(labelTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNewClient, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(postalCode)
                                .addGap(18, 18, 18)
                                .addComponent(txtPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(client)
                                .addGap(18, 18, 18)
                                .addComponent(cmbClients, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAuthenticate))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(name)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(firstName))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(btnSearch)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelResultResearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitle)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(firstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postalCode)
                    .addComponent(txtPostalCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSearch)
                    .addComponent(labelResultResearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(client)
                    .addComponent(btnAuthenticate)
                    .addComponent(cmbClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewClient)
                    .addComponent(btnBack))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Start the clients research in database
     * @param evt 
     */
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        
        cmbClients.removeAllItems();// empty the comboBox before any research
        
        String name = txtName.getText(), firstName = txtFirstName.getText(), postalCode = txtPostalCode.getText();
        
        if (name.isEmpty()) name = "%";
        if (firstName.isEmpty()) firstName = "%";
        if (postalCode.isEmpty()) postalCode = "%";
        
        try {
            clients = Client.getByNamePC(name, firstName, postalCode);
        } catch (SQLException ex) {
            Logger.getLogger(AuthenticationClientForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        labelResultResearch.setText(clients.size() + " résultat(s)");
        for (int i = 0; i < clients.size(); i++) {
            cmbClients.addItem(clients.get(i).getName() + ", " + clients.get(i).getFirstName() + ", " + clients.get(i).getCp());
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed
    
    /**
     * Start of ClientForm
     * @param evt 
     */
    private void btnNewClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewClientActionPerformed
        this.setVisible(false);
        new ClientForm().setVisible(true);
    }//GEN-LAST:event_btnNewClientActionPerformed
    
    /**
     * Start of SimulationForm with the selected client in parameter
     * @param evt 
     */
    private void btnAuthenticateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthenticateActionPerformed
        this.setVisible(false);
        Client client =  clients.get(cmbClients.getSelectedIndex());
        new SimulationForm(client).setVisible(true);
    }//GEN-LAST:event_btnAuthenticateActionPerformed
    
    /**
     * Back to SimulationMenuForm
     * @param evt 
     */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
        new SimulationMenuForm().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAuthenticate;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNewClient;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel client;
    private javax.swing.JComboBox cmbClients;
    private javax.swing.JLabel firstName;
    private javax.swing.JLabel labelResultResearch;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel name;
    private javax.swing.JLabel postalCode;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPostalCode;
    // End of variables declaration//GEN-END:variables
}
