package edu.hubanato.forms;

import edu.hubanato.controlers.ClientControl;

/**
 * @author Tom
 */
public class ClientForm extends javax.swing.JFrame {

    /**
     * Creates new form AuthenticationForm
     */
    public ClientForm() {
        initComponents();
        btnCreate.addActionListener(new ClientControl(cmbCivility, txtName, txtFirstName, jxDate, txtBirthPlace, cmbSex, cmbNationality, txtNb, txtStreet, txtAdd, txtCP, txtCity, cmbCountry, txtPNumber, txtPHome, txtPBusiness, txtEmail, txtJob, txtAge, cmbProfession, txtIncome, btnCreate, btnClear));
        btnClear.addActionListener(new ClientControl(cmbCivility, txtName, txtFirstName, jxDate, txtBirthPlace, cmbSex, cmbNationality, txtNb, txtStreet, txtAdd, txtCP, txtCity, cmbCountry, txtPNumber, txtPHome, txtPBusiness, txtEmail, txtJob, txtAge, cmbProfession, txtIncome, btnCreate, btnClear));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelName = new javax.swing.JLabel();
        labelFirstName = new javax.swing.JLabel();
        labelBirthDate = new javax.swing.JLabel();
        labelCivility = new javax.swing.JLabel();
        cmbCivility = new javax.swing.JComboBox();
        labelBirthPlace = new javax.swing.JLabel();
        labelNationality = new javax.swing.JLabel();
        labelStreetNumber = new javax.swing.JLabel();
        labelStreet = new javax.swing.JLabel();
        labelAdditional = new javax.swing.JLabel();
        labelPostalCode = new javax.swing.JLabel();
        labelCity = new javax.swing.JLabel();
        labelCountry = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        jxDate = new org.jdesktop.swingx.JXDatePicker();
        txtBirthPlace = new javax.swing.JTextField();
        txtNb = new javax.swing.JTextField();
        txtStreet = new javax.swing.JTextField();
        txtAdd = new javax.swing.JTextField();
        txtCP = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        labelPersonalNumber = new javax.swing.JLabel();
        labelHouseNumber = new javax.swing.JLabel();
        labelProNumber = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelWork = new javax.swing.JLabel();
        txtPBusiness = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtJob = new javax.swing.JTextField();
        labelTitle = new javax.swing.JLabel();
        labelMandatoryField = new javax.swing.JLabel();
        cmbNationality = new javax.swing.JComboBox();
        cmbCountry = new javax.swing.JComboBox();
        txtPNumber = new javax.swing.JTextField();
        labelSex = new javax.swing.JLabel();
        cmbSex = new javax.swing.JComboBox();
        txtCity = new javax.swing.JTextField();
        txtPHome = new javax.swing.JTextField();
        labelAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        labelPCS = new javax.swing.JLabel();
        cmbProfession = new javax.swing.JComboBox();
        labelIncome = new javax.swing.JLabel();
        txtIncome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form to create a client");

        labelName.setText("Nom * :");

        labelFirstName.setText("Prénom * :");

        labelBirthDate.setText("Date de naissance * :");

        labelCivility.setText("Civilité * :");

        cmbCivility.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M.", "Mme" }));

        labelBirthPlace.setText("Lieu de naissance * :");

        labelNationality.setText("Nationalité * :");

        labelStreetNumber.setText("N° * :");

        labelStreet.setText("Rue * :");

        labelAdditional.setText("Complément :");

        labelPostalCode.setText("Code postal * :");

        labelCity.setText("Ville * :");

        labelCountry.setText("Pays * :");

        btnCreate.setText("Créer le client");

        btnClear.setText("Vider les champs");

        labelPersonalNumber.setText("Numéro personnel * :");

        labelHouseNumber.setText("Numéro du domicile :");

        labelProNumber.setText("Numéro professionnel :");

        labelEmail.setText("Email *:");

        labelWork.setText("Travail :");

        labelTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(0, 51, 102));
        labelTitle.setText("Formulaire de création d'un client");

        labelMandatoryField.setForeground(new java.awt.Color(255, 0, 51));
        labelMandatoryField.setText("* Ce champ est obligatoire");

        cmbNationality.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Francaise", "Americaine", "Anglaise", "Japonaise", "Espagnole", "Italienne", "Allemande", "Portugaise" }));
        cmbNationality.setToolTipText("");

        cmbCountry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "France", "Italie", "Etats-Unis", "Royaume-Uni", "Espagne", "Grece", "Croatie", "Portugal" }));

        labelSex.setText("Sexe * :");

        cmbSex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));

        labelAge.setText("Age * :");

        txtAge.setPreferredSize(new java.awt.Dimension(60, 20));

        labelPCS.setText("Catégorie profesionnelle (PCS) * :");

        cmbProfession.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Agriculteur exploitant", "Artisan, commerçant et chef d'entreprise", "Cadre et profession intellectuelles supérieures", "Profession intermédiaire", "Employé", "Ouvrier", "Retraité", "Autre" }));

        labelIncome.setText("Revenu annuel (en € brut) * :");

        txtIncome.setPreferredSize(new java.awt.Dimension(60, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCivility)
                    .addComponent(labelName)
                    .addComponent(labelFirstName)
                    .addComponent(labelBirthDate)
                    .addComponent(labelBirthPlace)
                    .addComponent(labelStreetNumber)
                    .addComponent(labelStreet)
                    .addComponent(labelAdditional)
                    .addComponent(labelPostalCode)
                    .addComponent(labelCity)
                    .addComponent(labelNationality)
                    .addComponent(labelCountry)
                    .addComponent(labelSex))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(labelPersonalNumber))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelAge)
                                .addGap(18, 18, 18)
                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCity, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCountry, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbNationality, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbCivility, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jxDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(txtBirthPlace, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNb, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStreet, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAdd, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCP, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(labelHouseNumber))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelEmail)
                                            .addComponent(labelProNumber)
                                            .addComponent(labelWork)
                                            .addComponent(labelPCS)
                                            .addComponent(labelMandatoryField)
                                            .addComponent(labelIncome))))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPBusiness)
                                    .addComponent(txtEmail)
                                    .addComponent(txtJob)
                                    .addComponent(txtPNumber)
                                    .addComponent(txtPHome)
                                    .addComponent(cmbProfession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCreate)
                                .addGap(67, 67, 67)
                                .addComponent(btnClear)
                                .addGap(103, 103, 103)))))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTitle)
                .addGap(214, 214, 214))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitle)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCivility)
                    .addComponent(cmbCivility, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPersonalNumber)
                    .addComponent(txtPNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHouseNumber)
                    .addComponent(txtPHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelProNumber)
                    .addComponent(txtPBusiness, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBirthDate)
                    .addComponent(jxDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBirthPlace)
                    .addComponent(txtBirthPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelWork)
                    .addComponent(txtJob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSex)
                            .addComponent(cmbSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAge)
                            .addComponent(txtAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(119, 119, 119))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPCS)
                            .addComponent(cmbProfession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNationality)
                            .addComponent(cmbNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelIncome)
                            .addComponent(txtIncome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelStreetNumber)
                            .addComponent(txtNb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelStreet)
                            .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear)
                            .addComponent(btnCreate))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAdditional)
                    .addComponent(txtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPostalCode)
                    .addComponent(txtCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMandatoryField))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCountry)
                    .addComponent(cmbCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCreate;
    private javax.swing.JComboBox cmbCivility;
    private javax.swing.JComboBox cmbCountry;
    private javax.swing.JComboBox cmbNationality;
    private javax.swing.JComboBox cmbProfession;
    private javax.swing.JComboBox cmbSex;
    private org.jdesktop.swingx.JXDatePicker jxDate;
    private javax.swing.JLabel labelAdditional;
    private javax.swing.JLabel labelAge;
    private javax.swing.JLabel labelBirthDate;
    private javax.swing.JLabel labelBirthPlace;
    private javax.swing.JLabel labelCity;
    private javax.swing.JLabel labelCivility;
    private javax.swing.JLabel labelCountry;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelFirstName;
    private javax.swing.JLabel labelHouseNumber;
    private javax.swing.JLabel labelIncome;
    private javax.swing.JLabel labelMandatoryField;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelNationality;
    private javax.swing.JLabel labelPCS;
    private javax.swing.JLabel labelPersonalNumber;
    private javax.swing.JLabel labelPostalCode;
    private javax.swing.JLabel labelProNumber;
    private javax.swing.JLabel labelSex;
    private javax.swing.JLabel labelStreet;
    private javax.swing.JLabel labelStreetNumber;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelWork;
    private javax.swing.JTextField txtAdd;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBirthPlace;
    private javax.swing.JTextField txtCP;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtIncome;
    private javax.swing.JTextField txtJob;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNb;
    private javax.swing.JTextField txtPBusiness;
    private javax.swing.JTextField txtPHome;
    private javax.swing.JTextField txtPNumber;
    private javax.swing.JTextField txtStreet;
    // End of variables declaration//GEN-END:variables
}
