/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.hubanato.forms;

/**
 *
 * @author Tom
 */
public class LoanSummaryForm extends javax.swing.JFrame {

    /**
     * Create a new form LoanSummaryForm
     * @param amount
     * @param duration
     * @param rate
     * @param loanType
     */
    public LoanSummaryForm(int amount, int duration, double rate, String loanType) {
        initComponents();
        labelAmount.setText(labelAmount.getText() + " " + amount);
        labelDuration.setText(labelDuration.getText() + " " + duration);
        labelRate.setText(labelRate.getText() + " " + rate);
        labelType.setText(labelType.getText() + " " + loanType);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitle = new javax.swing.JLabel();
        labelAmount = new javax.swing.JLabel();
        labelDuration = new javax.swing.JLabel();
        labelRate = new javax.swing.JLabel();
        labelType = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelTitle.setText("Récapitulatif du prêt");

        labelAmount.setText("Montant (en €):");

        labelDuration.setText("Durée (en mois):");

        labelRate.setText("Taux (%):");

        labelType.setText("Type de prêt :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(labelTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelType)
                            .addComponent(labelAmount)
                            .addComponent(labelDuration)
                            .addComponent(labelRate))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelAmount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDuration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelRate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelType)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelAmount;
    private javax.swing.JLabel labelDuration;
    private javax.swing.JLabel labelRate;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelType;
    // End of variables declaration//GEN-END:variables
}
