/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.hubanato.forms;

import java.util.Observer;
import edu.hubanato.entities.RateVariable;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Observable;
import javax.swing.JFormattedTextField;

/**
 *
 * @author Baptiste
 */
public class PanelCharacteristics extends javax.swing.JPanel implements Observer{

     RateVariable rateVariable;

    /**
     * @param RateVariable 
     */
    public PanelCharacteristics(RateVariable rateVariable) {
        this.rateVariable = rateVariable;
        initComponents();
    }
    
    /**  */
    public PanelCharacteristics() {
        this(new RateVariable());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGCharacteristics = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        formattedTextAmount = new javax.swing.JFormattedTextField();
        formattedTextDuree = new javax.swing.JFormattedTextField();
        formattedTextCape = new javax.swing.JFormattedTextField();
        formattedTextRate = new javax.swing.JFormattedTextField();

        jLabel4.setText("Montant (en €):");

        jLabel3.setText("Taux:");

        jLabel2.setText("Capé:");

        jLabel1.setText("Durée (en années):");

        btnStart.setText("Lancer la simulation");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        formattedTextAmount.setToolTipText("");
        formattedTextAmount.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        formattedTextAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formattedTextAmountKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formattedTextAmountKeyTyped(evt);
            }
        });

        formattedTextDuree.setToolTipText("");
        formattedTextDuree.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formattedTextDureeKeyTyped(evt);
            }
        });

        formattedTextCape.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formattedTextCapeKeyTyped(evt);
            }
        });

        formattedTextRate.setEditable(false);
        formattedTextRate.setText("4.00");
        formattedTextRate.setEnabled(false);
        formattedTextRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formattedTextRateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelGCharacteristicsLayout = new javax.swing.GroupLayout(PanelGCharacteristics);
        PanelGCharacteristics.setLayout(PanelGCharacteristicsLayout);
        PanelGCharacteristicsLayout.setHorizontalGroup(
            PanelGCharacteristicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGCharacteristicsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formattedTextAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formattedTextDuree, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formattedTextCape, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formattedTextRate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGCharacteristicsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnStart)
                .addGap(221, 221, 221))
        );
        PanelGCharacteristicsLayout.setVerticalGroup(
            PanelGCharacteristicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGCharacteristicsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelGCharacteristicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(formattedTextAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formattedTextDuree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formattedTextCape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formattedTextRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnStart)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelGCharacteristics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelGCharacteristics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
 
        rateVariable.resetLists();
        rateVariable.stableRate(Double.parseDouble(this.formattedTextRate.getText()), Double.parseDouble(this.formattedTextDuree.getText()), Double.parseDouble(this.formattedTextAmount.getText()), Double.parseDouble(this.formattedTextCape.getText()));
//        rateVariable.stableRate((double) this.formattedTextRate.getValue(), (double) this.formattedTextDuree.getValue(), (double) this.formattedTextAmount.getValue(), (double) this.formattedTextCape.getValue());
        rateVariable.growthRate(Double.parseDouble(this.formattedTextRate.getText()), Double.parseDouble(this.formattedTextDuree.getText()), Double.parseDouble(this.formattedTextAmount.getText()), Double.parseDouble(this.formattedTextCape.getText()));
        rateVariable.decayRate(Double.parseDouble(this.formattedTextRate.getText()), Double.parseDouble(this.formattedTextDuree.getText()), Double.parseDouble(this.formattedTextAmount.getText()), Double.parseDouble(this.formattedTextCape.getText()));
        
    }//GEN-LAST:event_btnStartActionPerformed

    private void formattedTextRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formattedTextRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formattedTextRateActionPerformed

    private void formattedTextAmountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formattedTextAmountKeyPressed

    }//GEN-LAST:event_formattedTextAmountKeyPressed

    private void formattedTextAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formattedTextAmountKeyTyped
        char c = evt.getKeyChar();
        //the character is digital
        if (c >= '0' && c <= '9') {
            // System.out.println(evt);
        } else {
            //deleting the character
            evt.consume();
        }
    }//GEN-LAST:event_formattedTextAmountKeyTyped

    private void formattedTextDureeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formattedTextDureeKeyTyped
        char c = evt.getKeyChar();
        //the character is digital
        if (c >= '0' && c <= '9') {
            // System.out.println(evt);
        } else {
            //deleting the character
            evt.consume();
        }
    }//GEN-LAST:event_formattedTextDureeKeyTyped

    private void formattedTextCapeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formattedTextCapeKeyTyped
        char c = evt.getKeyChar();
        //the character is digital
        if (c >= '0' && c <= '9') {
            // System.out.println(evt);
        } else {
            //deleting the character
            evt.consume();
        }
    }//GEN-LAST:event_formattedTextCapeKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelGCharacteristics;
    private javax.swing.JButton btnStart;
    private javax.swing.JFormattedTextField formattedTextAmount;
    private javax.swing.JFormattedTextField formattedTextCape;
    private javax.swing.JFormattedTextField formattedTextDuree;
    private javax.swing.JFormattedTextField formattedTextRate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
   
    @Override
    public void update(Observable o, Object arg) {
    }

}
