package edu.hubanato.forms;

import edu.hubanato.client.TCPClient;
import edu.hubanato.entities.Client;
import edu.hubanato.entities.Simulation;
import java.io.IOException;
import java.sql.SQLException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.*;

/**
 *
 * @author Tom
 */
public class SimulationManagementForm extends javax.swing.JFrame {

    private List<Client> clients = new ArrayList<Client>();
    private List<Simulation> simulations = new ArrayList<Simulation>();
    private SimulationsTableModel tableModel;
    private Client selectedClient;
 
    private class SimulationsTableModel extends AbstractTableModel {

        private final String[] titles = {"Type de prêt", "Durée (en mois)", "Montant", "Taux d'intérêt" };
        private final List<Simulation> simulations;
        
        public void addSimulation(Simulation s) {
            int index = simulations.size();
            simulations.add(s);
            fireTableRowsInserted(index, index);
        }

        public Simulation getSimulationAt(int row) {
            if (row >= simulations.size()) {
                return null;
            } else {
                return simulations.get(row);
            }
        }

        public void deleteBookAt(int row){
            if (row < simulations.size()){
                simulations.remove(row);
                fireTableRowsDeleted(row, row);
            }
        }

        public SimulationsTableModel(List<Simulation> s) {
            simulations = s;
        }
        
        @Override
        public int getColumnCount() {
            return titles.length;
        }

        @Override
        public int getRowCount() {
            return simulations.size();
        }

        @Override
        public String getColumnName(int column) {
            return titles[column];
        }

        @Override
        public Object getValueAt(int row, int column) {
            switch (column) {
            case 0:
                return simulations.get(row).getLoanType();
            case 1:
                return simulations.get(row).getDuration();
            case 2:
                return simulations.get(row).getAmount();
            case 3:
                return simulations.get(row).getRate();
            default:
                return "";
            }
        }
    }
    
    public SimulationManagementForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        labelClient = new javax.swing.JLabel();
        btnShowSimulation = new javax.swing.JButton();
        labelTitle = new javax.swing.JLabel();
        cmbClients = new javax.swing.JComboBox();
        labelName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        labelFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        labelPostalCode = new javax.swing.JLabel();
        txtPostalCode = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        labelInformationClient = new javax.swing.JLabel();
        labelSimulations = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableSimulation = new javax.swing.JTable();
        btnReplaySimulation = new javax.swing.JButton();
        btnUpdateSimulation = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        labelNumberResults = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelClient.setText("Client :");

        btnShowSimulation.setText("Voir les simulations de ce client");
        btnShowSimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowSimulationActionPerformed(evt);
            }
        });

        labelTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(0, 51, 102));
        labelTitle.setText("Gestion d'une simulation");

        labelName.setText("Nom :");

        txtName.setPreferredSize(new java.awt.Dimension(100, 20));

        labelFirstName.setText("Prénom :");

        txtFirstName.setPreferredSize(new java.awt.Dimension(100, 20));

        labelPostalCode.setText("Code postal :");

        txtPostalCode.setPreferredSize(new java.awt.Dimension(50, 20));

        btnSearch.setText("Rechercher");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        labelInformationClient.setText("Veuillez renseigner les informations du client :");

        labelSimulations.setText("Simulations :");

        tableSimulation.setModel(new SimulationsTableModel(simulations));
        jScrollPane3.setViewportView(tableSimulation);

        btnReplaySimulation.setText("Rejouer cette simulation");
        btnReplaySimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReplaySimulationActionPerformed(evt);
            }
        });

        btnUpdateSimulation.setText("Modifier cette simulation");
        btnUpdateSimulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateSimulationActionPerformed(evt);
            }
        });

        btnBack.setText("Retour");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        labelNumberResults.setName(""); // NOI18N
        labelNumberResults.setPreferredSize(new java.awt.Dimension(100, 23));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnReplaySimulation)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdateSimulation)
                                .addGap(18, 18, 18)
                                .addComponent(btnBack))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(labelTitle))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(29, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelSimulations)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(labelClient)
                                            .addGap(13, 13, 13)
                                            .addComponent(cmbClients, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnShowSimulation))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(labelName)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(63, 63, 63)
                                            .addComponent(labelFirstName)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(labelPostalCode)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(31, 31, 31)
                                            .addComponent(btnSearch)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(labelNumberResults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelInformationClient)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitle)
                .addGap(28, 28, 28)
                .addComponent(labelInformationClient)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelPostalCode)
                    .addComponent(txtPostalCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearch)
                    .addComponent(labelNumberResults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelClient)
                    .addComponent(cmbClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShowSimulation))
                .addGap(18, 18, 18)
                .addComponent(labelSimulations)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReplaySimulation)
                    .addComponent(btnUpdateSimulation)
                    .addComponent(btnBack))
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowSimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowSimulationActionPerformed
        int index = cmbClients.getSelectedIndex();
        if (index == -1 ) {
            JOptionPane.showMessageDialog(null, "Veuillez selectionner un client.", "Erreur de selection",JOptionPane.ERROR_MESSAGE);
        } else {
            selectedClient =  clients.get(index);
            try {
                TCPClient tcpClient = new TCPClient("localhost",9999);
                tcpClient.sendQuery("gs", edu.hubanato.serialization.EncodeJSON.serializeInteger(selectedClient.getIdClient()));
                simulations = edu.hubanato.serialization.DecodeJSON.deserializeSimulations(tcpClient.receiveQuery());
            } catch (IOException ex) {
                Logger.getLogger(SimulationManagementForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            tableModel = new SimulationsTableModel(simulations);
            tableSimulation.setModel(tableModel);
        }
    }//GEN-LAST:event_btnShowSimulationActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        
        cmbClients.removeAllItems();
        
        String name = txtName.getText(), firstName = txtFirstName.getText(), postalCode = txtPostalCode.getText();

        if (name.isEmpty()) name = "%";
        if (firstName.isEmpty()) firstName = "%";
        if (postalCode.isEmpty()) postalCode = "%";

        try {
            TCPClient tcpClient = new TCPClient("localhost",9999);
            List<String> liste = new ArrayList<String>();
            liste.add(name); liste.add(firstName); liste.add(postalCode);
            tcpClient.sendQuery("gc", edu.hubanato.serialization.EncodeJSON.serializeListString(liste));
            clients = edu.hubanato.serialization.DecodeJSON.deserializeClients(tcpClient.receiveQuery());
        } catch (IOException ex) {
            Logger.getLogger(SimulationManagementForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        labelNumberResults.setText(clients.size() + " résultat(s)");
        for (int i = 0; i < clients.size(); i++) {
            cmbClients.addItem("Nom : " + clients.get(i).getName().toUpperCase() + " " + clients.get(i).getFirstName() +
                                " / Code postal : " + clients.get(i).getCp());
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnReplaySimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReplaySimulationActionPerformed
        int row = tableSimulation.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Veuillez selectionner une simulation.", "Erreur de selection",JOptionPane.ERROR_MESSAGE);
        } else {
            Simulation s =  simulations.get(row);
            new LoanSummaryForm(s.getAmount(), s.getDuration(), s.getRate(), s.getLoanType()).setVisible(true);
        }
    }//GEN-LAST:event_btnReplaySimulationActionPerformed

    private void btnUpdateSimulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateSimulationActionPerformed
        int row = tableSimulation.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Veuillez selectionner une simulation.", "Erreur de selection",JOptionPane.ERROR_MESSAGE);
        } else {
            Simulation s =  simulations.get(row);
            new SimulationUpdateForm(s, selectedClient).setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnUpdateSimulationActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
        new SimulationMenuForm().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimulationManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimulationManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimulationManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimulationManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimulationManagementForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReplaySimulation;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnShowSimulation;
    private javax.swing.JButton btnUpdateSimulation;
    private javax.swing.JComboBox cmbClients;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel labelClient;
    private javax.swing.JLabel labelFirstName;
    private javax.swing.JLabel labelInformationClient;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelNumberResults;
    private javax.swing.JLabel labelPostalCode;
    private javax.swing.JLabel labelSimulations;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JTable tableSimulation;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPostalCode;
    // End of variables declaration//GEN-END:variables
}
